### ISSUE TITLE
maybe set inheritAttrs:false is better?

### ISSUE THREAD

**Issue by agileago** [sxzz/vue-simple-props#48]
### Clear and concise description of the problem

maybe set inheritAttrs:false is better?

### Suggested solution

maybe set inheritAttrs:false is better?

### Alternative

maybe set inheritAttrs:false is better?

### Additional context

maybe set inheritAttrs:false is better?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Released as v0.4.0
