### ISSUE TITLE
一些优化及建议

### ISSUE THREAD

**Issue by agileago** [sxzz/vue-simple-props#50]
### Clear and concise description of the problem

这个库的思路真的特别棒，感觉vue的最佳实践就应该这个样子的，我想提几个优化点

## vue最佳实践

使用`tsx`

### 无状态组件

直接就是一个函数，根元素默认继承 `class` 和 `style`, 无需考虑其他东西

```tsx
interface AbcFunctionProps extends AllowedComponentProps {
  foo: string
}

function AbcFunction(props: AbcFunctionProps) {
  return <div>{props.foo}</div>
}
```

### 有状态组件

使用 `vue-simple-props` 

```tsx

interface AbcStateFunctionProps {
  foo: string
  onClick?: () => void
  renderFoo?: (count: number) => JSX.Element
  renderDefault?: () => JSX.Element
}

const AbcStateFunction = defineComponent<AbcStateFunctionProps>(props => {
  const count = ref(1)
  // 继承class和style
  const ics = useInheritClassAndStyle()

  return () => {
    return (
      <div {...ics}>
        <h3>我是AbcStateFunction组件</h3>
        <button onClick={() => count.value++}>+ {count.value}</button>
        {/* foo slot */}
        {props.renderFoo?.(count.value) || props.foo}
        {props.renderDefault?.()}
      </div>
    )
  }
})
```

## 优化点

- 导出 `defineComponent` 函数名, 一个一个 `as` 的话就特别麻烦
- 实现 `useInheritClassAndStyle` 函数可实现继承 `class` 和 `style` 功能， 实现函数式组件的类似的功能行为
- 建议寻找 `renderXXX` 属性时先优先从 `attrs` 中寻找，然后再从 `slots` 中查找， 因为有可能组件上面直接写渲染函数属性
- 优化点, 在 `attrs` 上面自动探测 `on` 开头事件优化组件渲染性能  
- 

```tsx
// 在 setup 函数中获取继承的 class 和 style
export function useInheritClassAndStyle(): { class?: any; style?: any } {
  const instance = getCurrentInstance()
  if (!instance) {
    throw new Error('useProps must be called inside setup()')
  }

  const attrs = useAttrs()

  return new Proxy(
    {},
    {
      get(target, p, receiver) {
        if (p === 'class' || p === 'style') {
          return Reflect.get(attrs, p, receiver)
        }
        return
      },
      ownKeys() {
        return ['class', 'style']
      },
      getOwnPropertyDescriptor(target, p) {
        if (p === 'class' || p === 'style') {
          return {
            enumerable: true,
            configurable: true,
          }
        }
        return
      },
    },
  )
}


function getEmits(attrs: Record<string, any>) {
  const emits: string[] = []
  for (const key in attrs) {
    if (key.startsWith('on')) {
      emits.push(key.slice(2).toLowerCase())
    }
  }
  return emits
}

instance.type.emits = getEmits(attrs)

```

### Alternative

-

### Additional context

-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by agileago** [comment]
@sxzz 怎么看其他优化点

**Comment by sxzz** [comment]
前两点建议已经实现。后两点没太搞懂，可以提供使用例子详述。

**Comment by agileago** [comment]
## 3. 寻找 renderXXX 属性时先优先从 attrs 中寻找，然后再从 slots 中查找， 因为有可能组件上面直接写渲染函数属性

就是说我定义了 组件属性如下

```tsx
interface AbcProps {
  renderFoo?: () => VNode
}

const Abc = defineComponent<AbcProps>(props => {
   return () => <div>{props.renderFoo?.()}</div>
})
```
这个时候当我在使用这个 `Abc` 组件的时候，我可以直接写 `renderFoo` 属性

```tsx
function App() {
  return <Abc renderFoo={() => <span>123</span>}></Abc>
}
```
但现在好像把 开头为 `render` 的属性给隐藏掉了， 并且在获取 `render` 开头的属性也获取不到了， 这块的设计我想的是你既然写了 有这个 `render` 属性，就应该让用户使用



## 4. 在 attrs 上面自动探测 on 开头事件优化组件渲染性能

因为 `vue` 会判断是否要更新组件时会有一个针对事件的判断，如果有 `on` 开头的属性，并且这个在 emits 中定义，即使他变化了，也不触发组件更新

https://github.com/vuejs/core/blob/4b608a9449fcfaa9c6105c96573ed30b599d2800/packages/runtime-core/src/componentRenderUtils.ts#L431-L444

这块可以做一个小优化

**Comment by agileago** [comment]
@sxzz

**Comment by sxzz** [comment]
经过测试，实际上在不指定 `emits` 时，并使用 `<Comp onClick={() => handler.value()} />`（给 `onClick` 传递一个新的闭包），并不会导致重复更新。

但如果指定了 `emits`，并使用 `<Comp onClick={handler.value} />`，反而会导致子组件无法得到新的 `handler.value`，而造成意外的问题。

所以在 `vue-simple-props` 中指定 `emits` 并无意义，反而会导致奇怪的问题。在 Vue SFC 中需要指定 `emits` 是因为我们使用的是 `emit` 函数来触发事件，它会得到最新的 handler。而我们这个情况下，直接调用的是 props 上的函数，则有此问题。

因此在本项目中，想避免不必要的更新，建议都使用闭包包裹一下。这也是 Vue SFC 在某些情况下编译的结果。

具体请参考此测试用例。https://github.com/sxzz/vue-simple-props/blob/3e4a47e12eee4e7bafc40a2de5d5009f87bad20b/tests/index.test.tsx#L161-L211

**Comment by sxzz** [comment]
The first three functions have been implemented, close this issue.

**Comment by agileago** [comment]
perfect! 这个名字感觉太长了  `defineFunctionalComponent `， 能不能导出一个 `defineComponent`, 这样就不用修改原来的代码了

**Comment by sxzz** [comment]
之前提及了，如果使用 `defineComponent` 容易重名，建议自行 `import { defineFunctionalComponent as defineComponent }` 或建一个文件自行封装 `export { defineFunctionalComponent as defineComponent } from 'vue-simple-props'`.

**Comment by agileago** [comment]
ok
