### ISSUE TITLE
Hyphenated attribute

### ISSUE THREAD

**Issue by erwinheldy** [sxzz/vue-simple-props#54]
### Clear and concise description of the problem

I use an ESLint rule that enforces the use of hyphenated attributes (https://eslint.vuejs.org/rules/attribute-hyphenation.html). However, using hyphenated attributes with this plugin is not working as expected. For example: https://stackblitz.com/edit/vitejs-vite-5vnu6s?file=src%2FApp.vue

### Suggested solution

It would be great if we could do both.
```vue
<script setup lang="ts">
import { Counter } from './Counter';
</script>

<template>
  <div class="flex gap-2">
    <Counter :initialCount="0" />
    <Counter :initial-count="0" />
  </div>
</template>

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Try `vue-simple-props@0.5.1`

**Comment by erwinheldy** [comment]
Thanks for the update. It works perfectly now.
