### ISSUE TITLE
support function name as component name property

### ISSUE THREAD

**Issue by agileago** [sxzz/vue-simple-props#56]
### Clear and concise description of the problem

```tsx
export const IconSimple = defineComponent(function IconSimple(props: IconSimpleProps) {
  return () => <div>icon simple1111 {props.count}</div>
})

console.log(IconSimple.name)
```
it is better set a function name as component name

### Suggested solution

it is better set a function name as component name

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Unable to set `name` automatically at runtime, but you can do it manually.
```ts
const Comp = defineFunctionalComponent(
  (props: Props) => {},
  {
    name: 'Comp',
    // other options, e.g. name, inheritAttrs, etc.
  },
)
export const Comp = defineSimpleComponent<Props>({
  name: 'Comp',
  setup() {},
})
```
