### ISSUE TITLE
函数支持传入第二个参数 ctx

### ISSUE THREAD

**Issue by agileago** [sxzz/vue-simple-props#60]
### Clear and concise description of the problem

```js
var a = function abc(params, ...args) {
  
}
a.length
```

这个函数 length 是 1，导致 vue 不会传入第二个参数 ctx

### Suggested solution

支持传入第二个参数

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Could you please provide your use case and a reproduction repository?

**Comment by agileago** [comment]
@sxzz

**Comment by sxzz** [comment]
Try `vue-simple-props@0.5.2`

**Comment by agileago** [comment]
expose类型还是错的，没有 expose 这个类型

**Comment by sxzz** [comment]
Try vue-simple-props@0.5.3
